SET DATABASE SQL SYNTAX ORA TRUE;
DROP TABLE USER IF EXISTS;
CREATE TABLE USER (
  userid INTEGER IDENTITY,
  login VARCHAR(255) NOT NULL,
  balance INTEGER DEFAULT 0,
  countKard INTEGER DEFAULT 0,
  createdDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
  );