SET DATABASE SQL SYNTAX ORA TRUE;
DROP TABLE KARD IF EXISTS;
CREATE TABLE KARD (
  kardid INTEGER IDENTITY,
  userid INTEGER NOT NULL,
  login VARCHAR(255) NOT NULL,
  kardName VARCHAR(255) NOT NULL,
  balance INTEGER DEFAULT 0 NOT NULL,
  createdDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updatedDate TIMESTAMP NOT NULL
);