SET DATABASE SQL SYNTAX ORA TRUE;
DROP TABLE USER IF EXISTS;
CREATE TABLE USER (
  userid INTEGER IDENTITY,
  login VARCHAR(255) NOT NULL,
  countKardOnUser INTEGER DEFAULT 0,
  allBalance INTEGER DEFAULT 0,
  createdUserDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
  );